version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 8088:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: passsword
    volumes:
      - ./data/db:/var/lib/postgresql/data
volumes:
  db-data:
